apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-shop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sudharshan-06/cloud-nativeshop.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-shop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true